# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Create folder structure
        run: |
          Write-Host "Running in $env:GITHUB_WORKSAPCE"
          New-Item -Path $env:GITHUB_WORKSPACE\build -ItemType Directory
          New-Item -Path $env:GITHUB_WORKSPACE\build\Mods -ItemType Directory
          New-Item -Path $env:GITHUB_WORKSPACE\build\Mods\Addons -ItemType Directory
          Copy-Item -Path $env:GITHUB_WORKSPACE\AT_AutoMountFeed -Destination $env:GITHUB_WORKSPACE\build\Mods\Addons -Recurse
          $LuaFiles = Get-ChildItem -Path $env:GITHUB_WORKSPACE\build\Mods\Addons -Recurse | Where-Object {
            $_.Extension -eq ".lua"
          }
          $LuaFiles | ForEach-Object {
            Write-Host "Compiling $($_.FullName)"
            Start-Process -FilePath $env:GITHUB_WORKSPACE\buildtools\luajit-2.0.5.exe -ArgumentList "-b $($_.FullName) $($_.FullName)c"
            Start-Sleep -Milliseconds 100
            Remove-Item -Path $_.FullName
          }
          $AllFiles = Get-ChildItem -Path $env:GITHUB_WORKSPACE\build\Mods\Addons -Recurse
          $AllFiles | ForEach-Object {
            Write-Host $_.FullName
          }
