name: Build AT_Notify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Checkout Git LFS
        run: git lfs pull

      - name: Create folder structure
        run: |
          Write-Host "Running in $env:GITHUB_WORKSAPCE"
          New-Item -Path $env:GITHUB_WORKSPACE\build\Mods\Addons -ItemType Directory -Force
          Copy-Item -Path $env:GITHUB_WORKSPACE\AT_Notify -Destination $env:GITHUB_WORKSPACE\build\Mods\Addons -Recurse

      - name: Compile lua
        run: |
          Set-Location -Path $env:GITHUB_WORKSPACE\buildtools
          Start-Process -FilePath ".\luajit-2.0.5.exe" -ArgumentList "-b $env:GITHUB_WORKSPACE\build\Mods\Addons\AT_Notify\Scripts\AT_Notify.lua $env:GITHUB_WORKSPACE\build\Mods\Addons\AT_Notify\Scripts\AT_Notify.luac"

      - name: Create pak
        env:
          VERSION_NUMBER: ${{ steps.version.outputs.version }}
        run: |
          Compress-Archive -Path $env:GITHUB_WORKSPACE\build\Mods -Destination $env:GITHUB_WORKSPACE\build\AT_Notify_$env:VERSION_NUMBER.pak
          Get-Item -Path "$env:GITHUB_WORKSPACE\build\AT_Notify_$env:VERSION_NUMBER.pak"
      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NUMBER: ${{ steps.version.outputs.version }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/AT_Notify_${{ steps.version.outputs.version }}.pak
          asset_name: AT_Notify_${{ steps.version.outputs.version }}.pak
          asset_content_type: application/zip